- hosts: localhost
#  connection: local
#  become: true
#  pre_tasks:
#    - name: update repos
#      apt:
#        update_cache: yes
#      changed_when: False  
#  tasks:
#  - name: create a file
#    file:
#      path: "/tmp/test_file_root1"
#      state: touch
#    become: yes
#
  tasks:
    - include: tasks/pacakges.yml
    - include: tasks/file.yml
