- hosts: localhost
  connection: local
  become: true
  
  tasks:
#  - name: create a file
#    file:
#      path: "/tmp/test_file1"
#      state: touch
#    become: yes
  - name: Install package
    apt:
      name:
        - htop
